[platformio]
default_envs = charge

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

[env:charge]
extends = env
build_src_filter =
	-<*>
	+<charge/main.cpp>

[env:discharge]
extends = env
build_src_filter =
	-<*>
	+<discharge/main.cpp>
